const ROLES = {
    ADMIN: 'ADMIN',
    HR: 'HR',
    REVIEWER: 'REVIEWER',
    CANDIDATE: 'CANDIDATE',
};

const ROLE_VALUES = Object.values(ROLES);

const WORK_MODES = {
    REMOTE: 'REMOTE',
    ONSITE: 'ONSITE',
    HYBRID: 'HYBRID',
};

const WORK_MODE_VALUES = Object.values(WORK_MODES);

const OFFER_TYPES = {
    FULL_TIME: 'FULL_TIME',
    PART_TIME: 'PART_TIME',
    INTERNSHIP: 'INTERNSHIP',
    CONTRACT: 'CONTRACT',
};

const OFFER_TYPE_VALUES = Object.values(OFFER_TYPES);

const OFFER_STATUSES = {
    DRAFT: 'DRAFT',
    OPEN: 'OPEN',
    CLOSED: 'CLOSED',
};

const OFFER_STATUS_VALUES = Object.values(OFFER_STATUSES);

const APPLICATION_STATUSES = {
    APPLIED: 'APPLIED',
    INVITED: 'INVITED',
    IN_PROGRESS: 'IN_PROGRESS',
    COMPLETED: 'COMPLETED',
    REJECTED: 'REJECTED',
    HIRED: 'HIRED',
};

const APPLICATION_STATUS_VALUES = Object.values(APPLICATION_STATUSES);

const QUESTION_TYPES = {
    MCQ_SINGLE: 'MCQ_SINGLE',
    MCQ_MULTI: 'MCQ_MULTI',
    TRUE_FALSE: 'TRUE_FALSE',
    SHORT_TEXT: 'SHORT_TEXT',
    ESSAY: 'ESSAY',
    CODE: 'CODE',
};

const QUESTION_TYPE_VALUES = Object.values(QUESTION_TYPES);

const AUTO_GRADED_QUESTION_TYPES = [
    QUESTION_TYPES.MCQ_SINGLE,
    QUESTION_TYPES.MCQ_MULTI,
    QUESTION_TYPES.TRUE_FALSE,
    QUESTION_TYPES.SHORT_TEXT,
];

const ATTEMPT_STATUSES = {
    NOT_STARTED: 'NOT_STARTED',
    IN_PROGRESS: 'IN_PROGRESS',
    SUBMITTED: 'SUBMITTED',
    GRADED: 'GRADED',
    EXPIRED: 'EXPIRED',
};

const ATTEMPT_STATUS_VALUES = Object.values(ATTEMPT_STATUSES);

module.exports = {
    ROLES,
    ROLE_VALUES,
    WORK_MODES,
    ATTEMPT_STATUSES,
    ATTEMPT_STATUS_VALUES,
    WORK_MODE_VALUES,
    OFFER_TYPES,
    OFFER_TYPE_VALUES,
    OFFER_STATUSES,
    OFFER_STATUS_VALUES,
    APPLICATION_STATUSES,
    APPLICATION_STATUS_VALUES,
    QUESTION_TYPES,
    QUESTION_TYPE_VALUES,
    AUTO_GRADED_QUESTION_TYPES,
};

